import { NgModule } from '@angular/core';
import {
  TuiValueChangesModule,
  TuiElementModule,
  TuiLetModule,
  TuiValidatorModule,
  TuiPortalModule,
} from '@taiga-ui/cdk';
import {
  TuiDataListModule,
  TuiTextfieldControllerModule,
  TuiButtonModule,
  TuiSvgModule,
  TuiCalendarModule,
  TuiGroupModule,
  TuiHintModule,
  TuiAlertModule,
  TuiDropdownModule,
  TuiPrimitiveCheckboxModule,
  TuiHostedDropdownModule,
  TuiExpandModule,
} from '@taiga-ui/core';
import {
  TuiDataListWrapperModule,
  TuiSelectModule,
  TuiProgressModule,
  TuiRadioLabeledModule,
  TuiComboBoxModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputNumberModule,
  TuiInputCountModule,
  TuiStepperModule,
  TuiInputModule,
  TuiInputPasswordModule,
  TuiRadioBlockModule,
  TuiRadioModule,
  TuiInputPhoneInternationalModule,
  TuiSortCountriesPipeModule,
  TuiInputPhoneModule,
  TuiCheckboxLabeledModule,
} from '@taiga-ui/kit';
import { TuiAppBarModule } from '@taiga-ui/addon-mobile';
import { TuiCardModule } from '@taiga-ui/addon-commerce';
import { TuiTableFiltersModule, TuiTableModule } from '@taiga-ui/addon-table';

@NgModule({
  imports: [
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiSelectModule,
    TuiTextfieldControllerModule,
    TuiButtonModule,
    TuiSvgModule,
    TuiProgressModule,
    TuiValueChangesModule,
    TuiRadioLabeledModule,
    TuiComboBoxModule,
    TuiLetModule,
    TuiElementModule,
    TuiCalendarModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiValidatorModule,
    TuiInputNumberModule,
    TuiInputCountModule,
    TuiGroupModule,
    TuiStepperModule,
    TuiInputModule,
    TuiInputPasswordModule,
    TuiInputDateModule,
    TuiRadioBlockModule,
    TuiRadioModule,
    TuiInputPhoneInternationalModule,
    TuiSortCountriesPipeModule,
    TuiInputPhoneModule,
    TuiCheckboxLabeledModule,
    TuiGroupModule,
    TuiPortalModule,
    TuiHintModule,
    TuiAlertModule,
    TuiDropdownModule,
    TuiTableModule,
    TuiTableFiltersModule,
    TuiPrimitiveCheckboxModule,
    TuiHostedDropdownModule,
    TuiAppBarModule,
    TuiExpandModule,
  ],
  exports: [
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiSelectModule,
    TuiTextfieldControllerModule,
    TuiButtonModule,
    TuiSvgModule,
    TuiProgressModule,
    TuiValueChangesModule,
    TuiRadioLabeledModule,
    TuiComboBoxModule,
    TuiLetModule,
    TuiElementModule,
    TuiCalendarModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiValidatorModule,
    TuiInputNumberModule,
    TuiInputCountModule,
    TuiGroupModule,
    TuiStepperModule,
    TuiInputModule,
    TuiInputPasswordModule,
    TuiInputDateModule,
    TuiRadioBlockModule,
    TuiRadioModule,
    TuiInputPhoneInternationalModule,
    TuiSortCountriesPipeModule,
    TuiInputPhoneModule,
    TuiCheckboxLabeledModule,
    TuiGroupModule,
    TuiPortalModule,
    TuiHintModule,
    TuiAlertModule,
    TuiCardModule,
    TuiInputModule,
    TuiDropdownModule,
    TuiTableModule,
    TuiTableFiltersModule,
    TuiPrimitiveCheckboxModule,
    TuiHostedDropdownModule,
    TuiAppBarModule,
    TuiExpandModule,
  ],
})
export default class SharedModule {}
