import { NgModule } from '@angular/core';
import {
  TuiElementModule,
  TuiValueChangesModule,
  TuiPortalModule,
} from '@taiga-ui/cdk';
import {
  TuiDataListModule,
  TuiTextfieldControllerModule,
  TuiButtonModule,
  TuiSvgModule,
  TuiGroupModule,
} from '@taiga-ui/core';
import {
  TuiDataListWrapperModule,
  TuiSelectModule,
  TuiProgressModule,
  TuiInputModule,
  TuiInputPasswordModule,
  TuiInputDateModule,
  TuiRadioBlockModule,
  TuiRadioModule,
  TuiInputPhoneInternationalModule,
  TuiSortCountriesPipeModule,
  TuiInputPhoneModule,
  TuiCheckboxLabeledModule,
} from '@taiga-ui/kit';

@NgModule({
  imports: [
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiSelectModule,
    TuiTextfieldControllerModule,
    TuiButtonModule,
    TuiSvgModule,
    TuiProgressModule,
    TuiValueChangesModule,
    TuiElementModule,
    TuiInputModule,
    TuiInputPasswordModule,
    TuiInputDateModule,
    TuiRadioBlockModule,
    TuiRadioModule,
    TuiInputPhoneInternationalModule,
    TuiSortCountriesPipeModule,
    TuiInputPhoneModule,
    TuiCheckboxLabeledModule,
    TuiGroupModule,
    TuiPortalModule,
  ],
  exports: [
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiSelectModule,
    TuiTextfieldControllerModule,
    TuiButtonModule,
    TuiSvgModule,
    TuiProgressModule,
    TuiValueChangesModule,
    TuiElementModule,
    TuiInputModule,
    TuiInputPasswordModule,
    TuiInputDateModule,
    TuiRadioBlockModule,
    TuiRadioModule,
    TuiInputPhoneInternationalModule,
    TuiSortCountriesPipeModule,
    TuiInputPhoneModule,
    TuiCheckboxLabeledModule,
    TuiGroupModule,
    TuiPortalModule,
  ],
})
export default class SharedModule {}
